### PR TITLE
Added getImprisonedCountByPearlType

### PR DESCRIPTION
**Pull request by Feathercrown**
Hope it works...
This is in preparation for being able to select which pearl types alban players

### CODE REVIEW

**Comment by Feathercrown** [comment]
If you accept the merge request for exilees not being altbanned, this must be accepted as well or it will break. I couldn't figure out how to do 2 files in 1 request. Accepting this request but not the other one doesn't break, but causes no gameplay changes.

**Comment by Feathercrown** [comment]
Oh hey I figured out multiple files.

**Comment by TealNerd** [comment]
This kinda breaks things with the prisonpearl integration, needs to not be a new method but a configurable change to the main getImprisonedCount method

**Comment by Feathercrown** [comment]
Oh yeah that makes a lot more sense.

Is there a way to search the whole project? I was wondering if getImprisonedCount was used in other places where I'd need to change it.

**Comment by TealNerd** [comment]
I would recommend importing it into eclipse (or whatever ide you use)

**Pull request closed without merging**
